disabled_rules:
  - colon
  - trailing_whitespace
  - unused_optional_binding
  - syntactic_sugar
  - multiple_closures_with_trailing_closure

excluded:
  - Carthage
  - Pods

line_length: 200

identifier_name: 
  excluded:
    - id
    - pk
